// Quelle: ArtikelApp.xlsx — Zeilenreihenfolge wie in der Tabelle.
// Spalten: Name, Preis, Gruppe (1=Getränke, 2=Speisen), Wo–So (x = aktiv). Standard: Mo, Di, Sa leer.
// Aeltere Excel nur Mi–So ab Spalte „Mi“: tool/generate_fruehlingsfest_seed.dart erkennt das.
// Nach Excel-Aenderung: tool/generate_fruehlingsfest_seed.dart anpassen und kArticleCatalogSeedVersion erhoehen.

const List<(String name, double price, int groupExcelId, bool mi, bool donnerstag, bool freitag, bool sonntag)>
    kFruehlingsfestArtikelSeed = [
  ('Bier 0,5l', 3.8, 1, true, true, true, true),
  ('Radler süß 0,5l', 3.8, 1, true, true, true, true),
  ('Radler sauer 0,5l', 3.8, 1, true, true, true, true),
  ('Alkoholfr. Bier 0,5l', 3.8, 1, true, true, true, true),
  ('Weizen 0,3l', 3, 1, true, true, true, true),
  ('ColaWeizen 0,3l', 3, 1, true, true, true, true),
  ('Russ süß 0,3l', 3, 1, true, true, true, true),
  ('Russ sauer 0,3l', 3, 1, true, true, true, true),
  ('Alkoholfr. Weizen 0,3l', 3, 1, true, true, true, true),
  ('Apfelschorle 0,5l', 3, 1, true, true, true, true),
  ('Spezi 0,5l', 3, 1, true, true, true, true),
  ('Cola 0,33l', 2.5, 1, true, true, true, true),
  ('Fanta 0,33l', 2.5, 1, true, true, true, true),
  ('Sprudel sauer 0,5l', 2.5, 1, true, true, true, true),
  ('Sprudel süß 0,5l', 2.5, 1, true, true, true, true),
  ('Wein rot', 4.5, 1, true, true, true, true),
  ('Wein weiß', 4.5, 1, true, true, true, true),
  ('Wein rose', 4.5, 1, true, true, true, true),
  ('Schorle Rot süß', 3.8, 1, true, true, true, true),
  ('Schorle Rot sauer', 3.8, 1, true, true, true, true),
  ('Schorle Weiß süß', 3.8, 1, true, true, true, true),
  ('Schorle Weiß sauer', 3.8, 1, true, true, true, true),
  ('Schorle Rosé süß', 3.8, 1, true, true, true, true),
  ('Schorle Rosé sauer', 3.8, 1, true, true, true, true),
  ('Flasche Wein 1l', 15, 1, true, true, true, true),
  ('Korea 0,5l', 7, 1, true, true, true, true),
  ('Kleines Bier 0,2l', 2.5, 1, true, true, true, true),
  ('Kleines Radler 0,2l', 2.5, 1, true, true, true, true),
  ('Weizen im Halbekrug', 6.5, 1, true, true, true, true),
  ('Schnaps', 2, 1, true, true, true, true),
  ('Kaffee', 1.5, 1, false, true, false, true),
  ('Kanne Kaffee', 8, 1, false, true, false, true),
  ('Kuchen', 2, 1, false, true, false, true),
  ('Torte', 2.5, 1, false, true, false, true),
  ('Schnitzel mit Pommes und Salat', 16, 2, false, false, false, true),
  ('Schnitzel halb/halb und Salat', 16, 2, false, false, false, true),
  ('Schnitzel mit Pommes', 12.5, 2, false, true, false, true),
  ('Schnitzel mit Kartoffelsalat', 12.5, 2, false, true, false, true),
  ('Schnitzel halb/halb', 12.5, 2, false, true, false, true),
  ('Schnitzel mit kleinem Salat', 12.5, 2, false, false, false, true),
  ('Paar Bratw. m. Kartoffelsalat', 10, 2, false, false, true, false),
  ('1 Bratw. m. Kartoffelsalat', 7, 2, false, false, true, false),
  ('Paar Bratw. m. Pommes', 10, 2, false, false, true, false),
  ('1 Bratw. m. Pommes', 7, 2, false, false, true, false),
  ('Hähnchen mit Brot', 8.5, 2, true, true, true, true),
  ('Hähnchen mit Pommes', 11.5, 2, true, true, true, true),
  ('Schlemmerpfanne mit Brot', 9, 2, true, true, true, true),
  ('Schlemmerpfanne mit Pommes', 12, 2, true, true, true, true),
  ('Schlemmerpfanne Kartoffelsalat', 12, 2, false, true, true, true),
  ('Schlemmerpfanne halb/halb', 12, 2, false, true, true, true),
  ('Rote Wurst', 3.8, 2, true, true, true, true),
  ('Rote mit Pommes', 6.8, 2, true, true, true, true),
  ('Currywurst', 4, 2, true, true, true, true),
  ('Currywurst mit Pommes', 7, 2, true, true, true, true),
  ('Pommes', 3, 2, true, true, true, true),
  ('Kartoffelsalat', 3, 2, false, true, true, true),
  ('Schnitzel mit Brot', 9, 2, true, true, true, true),
  ('Wecken', 0.6, 2, true, true, true, true),
];

/// Bei neuer Excel-Version erhoehen — ersetzt Artikel einmalig neu.
const int kArticleCatalogSeedVersion = 4;
